#package(default_visibility = ["//visibility:public"])
#
#apollo_cc_library(
#    name = "glog_init",
#    srcs = ["glog_init.cc"],
#    hdrs = ["glog_init.h"],
#    deps = ["@com_github_google_glog//:glog"],
#    alwayslink = 1, # Important
#)
