#load("//tools/proto:proto.bzl", "py_binary")
load("//tools:apollo_package.bzl", "apollo_package")
load("@rules_proto//proto:defs.bzl", "proto_library")


package(
    default_visibility = ["//visibility:public"],
)

py_binary(
    name = "cyber_performance",
    srcs = ["cyber_performance.py"],
)

#apollo_package()